# auto: true

markdown: rdiscount
highlighter: pygments
paginate: 8
permalink: /:title

title: kailiangchen
url: http://kailiangchen.me
feed: /atom.xml
author_info: <a href="http://kailiangchen.me/">kailiangchen</a>
